Initial Page
leoFagundes/cine-drivein-web pull request #2
Opened 2024-01-21 21:43 UTC by leoFagundes

2024-01-22 13:53 UTC, Sabanai104 requested changes

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Button/index.tsx
>      type: "button" | "submit" | "reset" | undefined;
Pode remover essa tipagem geralmente se utiliza a tipagem padrão de um button msm
```suggestion

```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Button/index.tsx
>      mainText?: string;
Só pra manter um padrão q geral tende a usar, também deixa essa prop como obrigatoria
```suggestion
    label: string;
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Button/index.tsx
>      onClick?: () => void;
Deixar obrigatoria
```suggestion
    onClick: () => void;
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Button/index.tsx
>          <button type={type} className={style.button} onClick={onClick}>
```suggestion
        <button className={style.button} onClick={onClick}>
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Button/index.tsx
> +export default function Button({ type, onClick, mainText }: Props) {
```suggestion
export default function Button({ onClick, mainText }: Props) {
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/CheckBox/index.tsx
>      onChange?: (isChecked: boolean) => void;
Deixa esses dois como obrigatorios, props q são essenciais para o funcionamento do componente devem ser passadas sempre como obrigatorias
```suggestion
    checked: boolean
    onChange: (isChecked: boolean) => void;
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/CheckBox/index.tsx
> +export default function CheckBox({ onChange, checked = false }: Props) {
Checkbox é uma palavra só, trocar em todos os lugares q estão CheckBox 
```suggestion
export default function Checkbox({ onChange, checked = false }: Props) {
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/CheckBox/index.tsx
> +import style from './CheckBox.module.scss'
```suggestion
import style from './Checkbox.module.scss'
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/LogoImage/LogoImage.module.scss
> +  margin-bottom: -70px;
A imagem q sua tia disponibilizou para você realmente está muito ruim, mas lembra q a gente arrumou ela no figma? Você consegue exportar as imagens q a gente já concertou pelo figma;

É só está com a imagem selecionada e ai vc tem a opção exportar 
![image](https://github.com/leoFagundes/cine-drivein-web/assets/51263792/e4483c94-fd9e-4a1d-a56a-5604b5e89e4d)



```suggestion
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/LogoImage/LogoImage.module.scss
> +  margin-bottom: -70px;
Com isso vc pode tirar esses estilos aii

2024-01-22 13:53 UTC, Sabanai104 commented on src/Components/Atoms/Text/index.tsx
> +        <p className={`${style.mainText} ${isLink ? style.isLink : ''}`}>
krl maneiro isso aqui, não conhecia

2024-01-22 13:53 UTC, Sabanai104 commented on src/Pages/Home/index.tsx
> +    const generateRandomName = () => {
Eu vi que essa função gera a string para passarmos para a api da imagem certo? Eu acho que o nome não condiz com o que faz, que tal trocarmos para.

```suggestion
    const getRandomDiceImageString = () => {
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Pages/Home/index.tsx
> +        let randomName = '';
```suggestion
        let randomString = '';
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Pages/Home/index.tsx
> +            randomName += characters.charAt(randomIndex);
```suggestion
            randomString += characters.charAt(randomIndex);
```

2024-01-22 13:53 UTC, Sabanai104 commented on src/Pages/Home/index.tsx
> +        return randomName;
```suggestion
        return randomString;
```

2024-01-24 16:06 UTC, leoFagundes commented on src/Components/Atoms/LogoImage/LogoImage.module.scss
> +  margin-bottom: -70px;
Ah belezinha, não sabia. Muito massa

2024-01-28 18:09 UTC, Sabanai104 approved these changes

2024-01-28 18:09 UTC, merged